' Autor: Sthefany Campos
@startuml
title Modelo de Banco de Dados

entity Usuario {
    * id : int
    --
    nome : varchar
    email : varchar
    senha : varchar
}

entity Lote {
    * id : int
    --
    nome : varchar
    quantidade_animais : int
}

entity Vacinacao {
    * id : int
    --
    vacina : varchar
    data_aplicacao : date
    data_proxima : date
    lote_id : int
}

entity Historico {
    * id : int
    --
    descricao : varchar
    data : date
    lote_id : int
}

Usuario ||--o{ Lote
Lote ||--o{ Vacinacao
Lote ||--o{ Historico

@enduml
